#!/bin/bash
#
#set -x

. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Load additional RunFunctions
. ./RunFunctionsSupplemental

export caseName=`basename $PWD`

#We stop this script when we encounter a problem
#trap "exit -1" ERR

echo "$caseName: Running blockMesh"
runApplicationAndReportOnError blockMesh

echo "$caseName: Updating the boundary file using  pyFoamInitMixingPlaneInterface.py"
# If not using pyFoamInitMixingPlaneInterface.py, a copy of a preconfigured
# boundary file is avaliable in constant/polyMesh/boundary.preconfigured

runApplicationAndReportOnError pyFoamInitMixingPlaneInterface.py . \
    mixpLeftOut mixpRightIn                           \
    --coordinateSystemType           coordinateSystem \
    --coordinateSystemOrigin         0 0 0.005        \
    --coordinateSystemE1             1 0 0            \
    --coordinateSystemE3             0 0 1            \
    --ribbonPatchDiscretisation      bothPatches      \
    --ribbonPatchStackAxis           Y                \
    --ribbonPatchSweepAxis           Z

echo "$caseName: Initializing the mixingPlane zones"
runApplicationAndReportOnError -l log.initMixingPlaneZones.sh ./initMixingPlaneZones.sh

echo "$caseName: Creating the starting time directory"
cp -r 0_orig 0

echo "$caseName: Running laplacianFoam"
runApplicationAndReportOnError laplacianFoam



