#!/bin/bash
#
#set -x

. $WM_PROJECT_DIR/bin/tools/RunFunctions

export caseName=`basename $PWD`

#We stop this script when we encounter a problem
#trap "exit -1" ERR

echo "$caseName: Creating the file blockMeshDict using m4"
(cd constant/polyMesh; m4 -P blockMeshDict.m4 > blockMeshDict)

echo "$caseName: Running blockMesh"
runApplicationAndReportOnError blockMesh

echo "$caseName: Updating the GGI and mixingPlane interfaces parameters"

# If not using pyFoamInitMixingPlaneInterface.py and pyFoamInitGgiInterface.py,
# a copy of a preconfigured boundary file is avaliable in
# constant/polyMesh/boundary.preconfigured

echo "Using pyFoamInitMixingPlaneInterface.py"
runApplicationAndReportOnError pyFoamInitMixingPlaneInterface.py . \
    upstreamMixingPlanePatch   downstreamMixingPlanePatch          \
    --coordinateSystemType           cylindrical \
    --coordinateSystemOrigin         0 0 0       \
    --coordinateSystemE1             1 0 0       \
    --coordinateSystemE3             0 0 1       \
    --ribbonPatchDiscretisation      bothPatches \
    --ribbonPatchStackAxis           Z           \
    --ribbonPatchSweepAxis           Theta


echo "Using pyFoamInitGgiInterface.py"
runApplicationAndReportOnError -l log1.pyFoamInitGgiInterface.py \
        pyFoamInitGgiInterface.py . upstreamPerio1 upstreamPerio2      \
        --type                   cyclicGgi \
        --rotationAxis           0 0 1     \
        --rotationAngle          36

runApplicationAndReportOnError -l log2.pyFoamInitGgiInterface.py \
        pyFoamInitGgiInterface.py . downstreamPerio1 downstreamPerio2 \
        --type                   cyclicGgi \
        --rotationAxis           0 0 1     \
        --rotationAngle          90

echo "$caseName: Creating the starting time directory"
cp -r 0_orig 0

echo "$caseName: Initializing the mixingPlane and GGI zones"
runApplicationAndReportOnError -l log.initMixingPlaneZones.sh ./initMixingPlaneZones.sh
runApplicationAndReportOnError -l log.initGgiZones.sh ./initGgiZones.sh

echo "$caseName: Running potentialFoam"
runApplicationAndReportOnError potentialFoam

echo "$caseName: Running simpleFoam"
runApplicationAndReportOnError simpleFoam


